spring:
  application:
    name: payment-service
  cloud:
    aws:
      region:
        static: ap-south-1
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres
    username: ${SUPABASE_USERNAME}
    password: ${SUPABASE_PASSWORD}
    hikari:
      maximum-pool-size: 3
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  mvc:
    servlet:
      path: /api/v1

aws:
  sqs:
    queue-name: order-events-queue
  sns:
    topic-arn: arn:aws:sns:ap-south-1:625189191389:payment-events-topic

server:
  port: 8082

razorpay:
  key-id: ${RAZORPAY_KEY_ID:}
  key-secret: ${RAZORPAY_KEY_SECRET:}
  webhook-secret: ${RAZORPAY_WEBHOOK_SECRET:}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

