spring:
  application:
    name: order-service
  cloud:
    aws:
      region:
        static: ap-south-1
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres
    username: ${SUPABASE_USERNAME}
    password: ${SUPABASE_PASSWORD}
    hikari:
      maximum-pool-size: 3
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  mvc:
    servlet:
      path: /api/v1

aws:
  sns:
    topic:
      order-events: arn:aws:sns:ap-south-1:625189191389:order-events
  sqs:
    payment-events-queue: ${PAYMENT_EVENTS_QUEUE:order-payment-events-queue}

server:
  port: 8081

logging:
  level:
    com.sj.ecommerce.order_service: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always